### ISSUE TITLE
Matrix->Slack messages don't work

### ISSUE THREAD

**Issue by neutralinsomniac** [kfatehi/matrix-puppet-slack#3]
This error shows up quite frequently:

```
TypeError: Cannot read property 'getAliases' of null
    at App.getThirdPartyRoomIdFromMatrixRoomId (/home/jeremy/matrix-puppet-slack/node_modules/matrix-puppet-bridge/src/base.js:99:16)
    at teamAppList.reduce (/home/jeremy/matrix-puppet-slack/index.js:86:35)
    at Array.reduce (native)
    at Promise (/home/jeremy/matrix-puppet-slack/index.js:84:33)
    at Promise._execute (/home/jeremy/matrix-puppet-slack/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/jeremy/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/jeremy/matrix-puppet-slack/node_modules/bluebird/js/release/promise.js:77:14)
    at getAndCacheAppFromMatrixRoomId (/home/jeremy/matrix-puppet-slack/index.js:79:14)
    at Object.onEvent (/home/jeremy/matrix-puppet-slack/index.js:108:13)
    at Bridge._onConsume (/home/jeremy/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/bridge.js:664:30)
    at /home/jeremy/matrix-puppet-slack/node_modules/matrix-appservice-bridge/lib/bridge.js:838:14
    at tryCatcher (/home/jeremy/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/jeremy/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/jeremy/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/jeremy/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/jeremy/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/jeremy/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/jeremy/matrix-puppet-slack/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by neutralinsomniac** [comment]
config.json:
```
{                                                                                                                                                                                                                
  "slack": [                                                                                                                                                                                                     
    {                                                                                                                                                                                                            
      "team_name": "pintobyte",                                                                                                                                                                                  
      "user_access_token": "..."                                                                                                            
    }                                                                                                                                                                                                            
  ],                                                                                                                                                                                                             
  "registrationPath": "slack-registration.yaml",                                                                                                                                                                 
  "port": 8092,                                                                                                                                                                                                  
  "bridge": {                                                                                                                                                                                                    
    "homeserverUrl": "https://pintobyte.com:8448",                                                                                                                                                               
    "domain": "pintobyte.com",                                                                                                                                                                                   
    "registration": "slack-registration.yaml"                                                                                                                                                                    
  },                                                                                                                                                                                                             
  "puppet": {                                                                                                                                                                                                    
    "id": "@piroko:pintobyte.com",                                                                                                                                                                               
    "localpart": "piroko",                                                                                                                                                                                       
    "token": "..."                                                                                                                                                
  }                                                                                                                                                                                                              
}
```

**Comment by neutralinsomniac** [comment]
slack-registration.yaml:
```
id: ...                                                                                                                                             
hs_token: ...                                                                                                                                       
as_token: ...                                                                                                                                       
namespaces:                                                                                                                                                                                                      
  users:                                                                                                                                                                                                         
    - exclusive: true                                                                                                                                                                                            
      regex: '@slack_.*'                                                                                                                                                                                         
  aliases: []                                                                                                                                                                                                    
  rooms: []                                                                                                                                                                                                      
url: 'http://127.0.0.1:8092'                                                                                                                                                                                     
sender_localpart: slack_bot                                                                                                                                                                                      
rate_limited: true  
```
